name: 'Deploy Application'
description: 'Deploy the Mandelbrot Set Visualizer application'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'production'
runs:
  using: 'composite'
  steps:
    - name: Deploy to environment
      run: bash ${{ github.action_path }}/deploy.sh ${{ inputs.environment }}
      shell: bash
