name: 'Deploy Application'
description: 'Deploy the Mandelbrot Set Visualizer application'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'production'
runs:
  using: 'node12'
  main: 'deploy.js'
