name: 'Deploy Application'
description: 'Deploy the Mandelbrot Set Visualizer application'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
    default: 'production'
runs:
  using: 'composite'
  steps:
    - name: Deploy to environment
      run: bash ${{ github.action_path }}/deploy.sh ${{ inputs.environment }}
      shell: bash    


#for windows runner environment deployment include the below run commands in Action.yml
#runs:
#  using: 'node12'
#  main: 'deploy.js'
