name: ICA2 Group 3 Github Action CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build-and-Test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: echo "Pip and dependencies installation placeholder"
      - run: echo "Test execution placeholder"

        # Ensure this command runs your tests. Update if tests are in a different directory

      # Temporarily commenting out until test report generation is set up
      # - name: Upload test report as an artifact
      #   uses: actions/upload-artifact@v2
      #   if: always() # Ensures this step runs even if tests fail
      #   with:
      #     name: test-reports
      #     path: test-reports/ # Update with actual path where test reports are stored

  Dockerize-Application:
    needs: Build-and-Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/ravitejadocker8698/my-python-app:latest .
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push ghcr.io/ravitejadocker8698/my-python-app:latest

  Integration-Test:
    needs: Dockerize-Application
    runs-on: self-hosted
    services:
      app:
        image: ghcr.io/ravitejadocker8698/my-python-app:latest
        ports:
          - 5001:5000
    steps:
      - uses: actions/checkout@v2

      - name: Run integration tests
        run: |
          # Replace this with actual commands to run integration tests
          curl http://localhost:5001/
          # Example placeholder for testing purpose

  Deploy:
    needs: Integration-Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Custom Deployment Action
        uses: ./.github/actions/deploy-action
        with:
          environment: 'production'
