name: "ICA2 CI/CD pipeline"

on:
  push:
    branches:
      - main

jobs:
  Build-and-Test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash

      - name: Run Unit Tests
        run: python test_app.py
        shell: bash

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test-reports
          path: test-reports/

  Dockerize-application:
    needs: Build-and-Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        shell: bash

      - name: Build and push Docker image
        run: docker build -t ghcr.io/raviteja869/mandelbrot-set-visualizer:latest . && docker push ghcr.io/raviteja869/mandelbrot-set-visualizer:latest
        shell: bash

  Integration-Test:
    needs: Dockerize-application
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Check Port Availability
        run: netstat -tuln | grep :5000 || echo "Port 5000 is available"
        shell: bash

      - name: Start Dockerized Application
        run: docker run -d -p 5000:5000 ghcr.io/raviteja869/mandelbrot-set-visualizer:latest
        shell: bash

      - name: Run Integration Tests
        run: bash ./run_integration_tests.sh
        shell: bash

  Deploy:
    needs: Integration-Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Custom Deployment Action
        uses: ./.github/actions/deploy-action
        with:
          environment: 'production'
