name: "ICA2 CI/CD pipeline"

on:
  push:
    branches:
      - main

jobs:
  Build-and-Test:
    runs-on: self-hosted
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Setup Python
          uses: actions/setup-python@v4.7.1
          with:
            python-version: "3.9"
        - name: Setup Poetry environment
          uses: 5yutan5/setup-poetry-env@v1.1.0
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.3
          with:
             name: test-reports
             path: test-reports/
          
          
       
