name: "ICA2 CI/CD pipeline"

on:
  push:
    branches:
      - main

jobs:
  Build-and-Test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
      - name: Python Dependency Installation
        run: pip install -r requirements.txt
        shell: cmd
      - name: Run Unit Tests
        run: python test_app.py
        shell: cmd
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test-reports
          path: test-reports/

  Dockerize-application:
    needs: Build-and-Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        shell: cmd
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/raviteja869/mandelbrot-set-visualizer:latest .
          docker push ghcr.io/raviteja869/mandelbrot-set-visualizer:latest
        shell: cmd

  Integration-Test:
    needs: Dockerize-application
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Check Port Availability
        run: |
          netstat -ano | findstr :5000
          if errorlevel 1 (
            echo "Port 5000 is available"
          ) else (
            echo "Port 5000 is in use. Stopping the running container."
            FOR /F "tokens=*" %%i IN ('docker ps -q -f "publish=5000"') DO docker stop %%i
          )
        shell: cmd
      - name: Start Dockerized Application
        run: docker run -d -p 5000:5000 ghcr.io/raviteja869/mandelbrot-set-visualizer:latest
        shell: cmd
      - name: Run Integration Tests
        run: cmd /c run_integration_tests.bat
        shell: cmd
  Deploy:
    needs: Integration-Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Custom Deployment Action
        uses: ./.github/actions/deploy-action
        with:
          environment: 'production'
