name: "ICA2 CI/CD pipeline"

on:
  push:
    branches:
      - main

jobs:
  Build-and-Test:
    runs-on: self-hosted
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Setup Python
          uses: actions/setup-python@v4.7.1
        - name: Install dependencies using Poetry
          uses: Steffo99/actions-poetry-deps@v0.2.5
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.3
          with:
             name: test-reports
             path: test-reports/
          
          
       
